/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radio;

/**
 *
 * @author cim111
 */
public class RadioGUI extends javax.swing.JPanel {

    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        power = new javax.swing.JToggleButton();
        bandSwitch = new javax.swing.JToggleButton();
        favoriteOne = new javax.swing.JButton();
        favoriteTwo = new javax.swing.JButton();
        favoriteThree = new javax.swing.JButton();
        favoriteFour = new javax.swing.JButton();
        favoriteFive = new javax.swing.JButton();
        favoriteSix = new javax.swing.JButton();
        setFavorite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diaplay = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        power.setText("On");

        bandSwitch.setText("AM");
        bandSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandSwitchActionPerformed(evt);
            }
        });

        favoriteOne.setText("1");

        favoriteTwo.setText("2");

        favoriteThree.setText("3");

        favoriteFour.setText("4");

        favoriteFive.setText("5");

        favoriteSix.setText("6");

        setFavorite.setText("Set");

        diaplay.setColumns(20);
        diaplay.setRows(5);
        jScrollPane1.setViewportView(diaplay);

        jButton1.setText("<<");

        jButton2.setText(">>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setFavorite)
                            .addComponent(power)
                            .addComponent(bandSwitch))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(favoriteOne)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(favoriteTwo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(favoriteThree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(favoriteFour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(favoriteFive)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(favoriteSix)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(power)
                        .addGap(18, 18, 18)
                        .addComponent(bandSwitch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setFavorite)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favoriteOne)
                    .addComponent(favoriteTwo)
                    .addComponent(favoriteThree)
                    .addComponent(favoriteFour)
                    .addComponent(favoriteFive)
                    .addComponent(favoriteSix))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bandSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandSwitchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bandSwitchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bandSwitch;
    private javax.swing.JTextArea diaplay;
    private javax.swing.JButton favoriteFive;
    private javax.swing.JButton favoriteFour;
    private javax.swing.JButton favoriteOne;
    private javax.swing.JButton favoriteSix;
    private javax.swing.JButton favoriteThree;
    private javax.swing.JButton favoriteTwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton power;
    private javax.swing.JButton setFavorite;
    // End of variables declaration//GEN-END:variables
}
